name: coverage

on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          go version
      - name: Build
        run: go build .

      - name: Test With Coverage
        run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
