name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been modified
on:
  workflow_dispatch: # allow running workflow manually
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths:
      - "**.proto"
jobs:
  proto-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker-practice/actions-setup-docker@master
      - name: lint
        run: make proto-lint
      - name: check-breakage
        run: make proto-check-breaking-ci
