name: Proto check
on: [pull_request]
jobs:
  proto-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker-practice/actions-setup-docker@master
      - name: lint
        run: make proto-lint
      - name: check-breakage
        run: make proto-check-breaking-ci
